message( "\nConfiguring Boost:\n" )
find_package(Boost QUIET)
if (Boost_FOUND)
	message( "-- Boost found.")
else (Boost_FOUND)
	message( "-- Boost not found in system path. Looking in 3rdParty folder...")

	find_subdirs( ${CMAKE_CURRENT_SOURCE_DIR}/3rdParty "boost")
	
	list(LENGTH SUBDIRS SUBDIR_COUNT)
	while((SUBDIR_COUNT GREATER 0) AND (NOT Boost_FOUND))
		list(POP_FRONT SUBDIRS SUBDIR)
		set (PTH "${CMAKE_CURRENT_SOURCE_DIR}/3rdParty/${SUBDIR}")
		if(IS_DIRECTORY ${PTH} AND EXISTS "${PTH}/boost/version.hpp")
			set(Boost_INCLUDE_DIR ${PTH} CACHE PATH "Boost directory" FORCE)
			find_package(Boost QUIET)
		endif()
		list(LENGTH SUBDIRS SUBDIR_COUNT)
	endwhile()
	
	if (Boost_FOUND)
		message( "-- Boost found in ${PTH}" )
	else (Boost_FOUND)
		message( "-- Boost not found. Specify Boost_INCLUDE_DIR variable and reconfigure, please...")
	endif (Boost_FOUND)
endif (Boost_FOUND)
